version: '3.9'

services:

  api:
    build: .
    container_name: auth-api
    depends_on:
      - postgres
      - redis
    networks:
      - auth_network
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - YOUR_PATH_TO_PROJECT:/app

  redis:
    image: redis:7.0.10
    container_name: auth-redis
    volumes:
      - auth-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 30s
    restart: unless-stopped
    networks:
      - auth_network
    ports:
      - 6379
    env_file:
      - .env

  postgres:
    image: postgres:13
    container_name: auth-postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - auth_network
    env_file:
      - .env

volumes:
  auth-redis-data:
  auth-db-data:

networks:
  auth_network:
